### PR TITLE
Use BIP39 for seed generation for new wallets

### PR DESCRIPTION
**Pull request by jcramer**
* Adds new wallet type called "bip39-slp" to prevent backwards compatibility
* All new wallets seeds use bip39 seeds
* Uses BIP44 coin type 245 to derive xprv, xpub,  and addresses

### CODE REVIEW

**Comment by jcramer** [comment]
Please let me know if this is the right approach.  Seems to work fine for me, but I wasn't able to verify that the xprv and xpub keys in the wallet file are correct.  The addresses generated seem to be correct for the path m/44'/245'/0'/0

**Comment by jcramer** [comment]
Also there are more changes to be made to the UI, I just wanted to make sure the core is done correctly before moving on

**Comment by fyookball** [comment]
Will take a look.  You should verify against ian coleman bip39 tool in the meantime

**Comment by fyookball** [comment]
seems ok. my 2 cents:

1. i tested with ian coleman tool. seems to get the same xpub, so that's good.

2. i couldnt really test the whole thing you did because its not preventing normal wallet from opening but when i create the slp-bip39 wallet, it doesnt know about it so i cant actually open it once i create the wallet. obviously needs that before a release can be done.

3. i dont understand what the code is doing with the passphrase. how does that impact bip39?

4. interesting that you import pbkdf2 separately vs calling hashlib version of it. not sure how this relates to the fact we use pbkdf2 in setup.py. why use another import if we dont have to.

**Comment by jcramer** [comment]
> 2. i couldnt really test the whole thing you did because its not preventing normal wallet from opening but when i create the slp-bip39 wallet, it doesnt know about it so i cant actually open it once i create the wallet. obviously needs that before a release can be done.

did you see the latest commit? Maybe this fixes this problem?

**Comment by markblundeberg** [comment]
Hey @jcramer I don't have time to look at it in detail, but I'm curious: will this add support for bip39 seed storage in the 'keystore' object? As I recall that was one problem with Electrum/Electron Cash, that you can import bip39 but not export it.

**Comment by jcramer** [comment]
> Hey @jcramer I don't have time to look at it in detail, but I'm curious: will this add support for bip39 seed storage in the 'keystore' object? As I recall that was one problem with Electrum/Electron Cash, that you can import bip39 but not export it.

Hey @markblundeberg. As is, if you create a new wallet the seed phrase is in the wallet file (within keystore), but if you import from bip39 then the keystore does not contain the imported seed phrase.

**Comment by markblundeberg** [comment]
Aww, too bad. I think such full bip39 support would be nice to have in EC as well. Although there are weird things with bip39 like added custom words, etc. that make it way more complicated

**Pull request merged**
